{ lib, ... }: let
  userfile = import ../../_lib/userfile.nix { inherit lib; };
in {
  flake.nixosModules.hyprland = { pkgs, ... }: let
    # Delivered via HYPRLAND_CONFIG so Hyprland never falls back to an
    # autogenerated config, with a ~/.config symlink as a second safety net.
    conf = pkgs.writeText "hyprland.conf" (builtins.readFile ./hyprland.conf);
  in
    {
      programs.hyprland = {
        enable = true;
        withUWSM = true;
      };
      security.pam.services.hyprlock = { };
      environment.systemPackages = [ pkgs.hyprsunset ];
      environment.sessionVariables.HYPRLAND_CONFIG = "${conf}";
    }
    // userfile {
      user = "frittata";
      file = ".config/hypr/hyprland.conf";
      source = conf;
    };
}
