#!/usr/bin/env zsh

export __NV_PRIME_RENDER_OFFLOAD=1
export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only

# exec "$@" forwards any arguments you pass to this script 
# (e.g., running `nvidia-offload blender` runs blender with these variables)
exec "$@"
